In [1]:
pip install git+https://github.com/huggingface/transformers

Collecting git+https://github.com/huggingface/transformers
  Cloning https://github.com/huggingface/transformers to /tmp/pip-req-build-uu83nt3p
  Running command git clone --filter=blob:none --quiet https://github.com/huggingface/transformers /tmp/pip-req-build-uu83nt3p
  Resolved https://github.com/huggingface/transformers to commit b6d65e40b256d98d9621707762b94bc8ad83b7a7
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Requirement already satisfied: filelock in /usr/local/lib/python3.11/dist-packages (from transformers==4.52.0.dev0) (3.18.0)
Requirement already satisfied: huggingface-hub<1.0,>=0.30.0 in /usr/local/lib/python3.11/dist-packages (from transformers==4.52.0.dev0) (0.30.2)
Requirement already satisfied: numpy>=1.17 in /usr/local/lib/python3.11/dist-packages (from transformers==4.52.0.dev0) (2.0.2)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.11/dist-packages (from transformers==4.52.0.dev0) (24.2)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.11/dist-packages (from transformers==4.52.0.dev0) (6.0.2)
Requirement already satisfied: regex!=2019.12.17 in /usr/local/lib/python3.11/dist-packages (from transformers==4.52.0.dev0) (2024.11.6)
Requirement already satisfied: requests in /usr/local/lib/python3.11/dist-packages (from transformers==4.52.0.dev0) (2.32.3)
Requirement already satisfied: tokenizers<0.22,>=0.21 in /usr/local/lib/python3.11/dist-packages (from transformers==4.52.0.dev0) (0.21.1)
Requirement already satisfied: safetensors>=0.4.3 in /usr/local/lib/python3.11/dist-packages (from transformers==4.52.0.dev0) (0.5.3)
Requirement already satisfied: tqdm>=4.27 in /usr/local/lib/python3.11/dist-packages (from transformers==4.52.0.dev0) (4.67.1)
Requirement already satisfied: fsspec>=2023.5.0 in /usr/local/lib/python3.11/dist-packages (from huggingface-hub<1.0,>=0.30.0->transformers==4.52.0.dev0) (2025.3.2)
Requirement already satisfied: typing-extensions>=3.7.4.3 in /usr/local/lib/python3.11/dist-packages (from huggingface-hub<1.0,>=0.30.0->transformers==4.52.0.dev0) (4.13.2)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.11/dist-packages (from requests->transformers==4.52.0.dev0) (3.4.1)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.11/dist-packages (from requests->transformers==4.52.0.dev0) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.11/dist-packages (from requests->transformers==4.52.0.dev0) (2.3.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.11/dist-packages (from requests->transformers==4.52.0.dev0) (2025.1.31)
Building wheels for collected packages: transformers
  Building wheel for transformers (pyproject.toml) ... done
  Created wheel for transformers: filename=transformers-4.52.0.dev0-py3-none-any.whl size=11455925 sha256=715d25cfddde2b3dc43106608032ed53c52e986bcaa5836ad46b7bf3076d5065
  Stored in directory: /tmp/pip-ephem-wheel-cache-qxa035m9/wheels/04/a3/f1/b88775f8e1665827525b19ac7590250f1038d947067beba9fb
Successfully built transformers
Installing collected packages: transformers
  Attempting uninstall: transformers
    Found existing installation: transformers 4.51.3
    Uninstalling transformers-4.51.3:
      Successfully uninstalled transformers-4.51.3
Successfully installed transformers-4.52.0.dev0

In [23]:
!pip install kaggle

Requirement already satisfied: kaggle in /usr/local/lib/python3.11/dist-packages (1.7.4.2)
Requirement already satisfied: bleach in /usr/local/lib/python3.11/dist-packages (from kaggle) (6.2.0)
Requirement already satisfied: certifi>=14.05.14 in /usr/local/lib/python3.11/dist-packages (from kaggle) (2025.1.31)
Requirement already satisfied: charset-normalizer in /usr/local/lib/python3.11/dist-packages (from kaggle) (3.4.1)
Requirement already satisfied: idna in /usr/local/lib/python3.11/dist-packages (from kaggle) (3.10)
Requirement already satisfied: protobuf in /usr/local/lib/python3.11/dist-packages (from kaggle) (5.29.4)
Requirement already satisfied: python-dateutil>=2.5.3 in /usr/local/lib/python3.11/dist-packages (from kaggle) (2.8.2)
Requirement already satisfied: python-slugify in /usr/local/lib/python3.11/dist-packages (from kaggle) (8.0.4)
Requirement already satisfied: requests in /usr/local/lib/python3.11/dist-packages (from kaggle) (2.32.3)
Requirement already satisfied: setuptools>=21.0.0 in /usr/local/lib/python3.11/dist-packages (from kaggle) (75.2.0)
Requirement already satisfied: six>=1.10 in /usr/local/lib/python3.11/dist-packages (from kaggle) (1.17.0)
Requirement already satisfied: text-unidecode in /usr/local/lib/python3.11/dist-packages (from kaggle) (1.3)
Requirement already satisfied: tqdm in /usr/local/lib/python3.11/dist-packages (from kaggle) (4.67.1)
Requirement already satisfied: urllib3>=1.15.1 in /usr/local/lib/python3.11/dist-packages (from kaggle) (2.3.0)
Requirement already satisfied: webencodings in /usr/local/lib/python3.11/dist-packages (from kaggle) (0.5.1)

In [34]:
from transformers import pipeline
import pandas as pd
import numpy as np

In [35]:
text_classifier = pipeline("sentiment-analysis")

No model was supplied, defaulted to distilbert/distilbert-base-uncased-finetuned-sst-2-english and revision 714eb0f (https://huggingface.co/distilbert/distilbert-base-uncased-finetuned-sst-2-english).
Using a pipeline without specifying a model name and revision in production is not recommended.
Device set to use cpu

In [36]:
from google.colab import userdata
airline_reviews = userdata.get('airline_reviews_dataset')

In [37]:
airline_reviews_df = pd.read_csv(airline_reviews)

airline_reviews_df = airline_reviews_df.head(50)

In [38]:
airline_reviews_df.shape

(50, 20)

In [39]:
example = airline_reviews_df['ReviewHeader'][2]

In [40]:
text_classifier(example)

[{'label': 'POSITIVE', 'score': 0.9995362758636475}]

In [41]:
for index, row in airline_reviews_df.iterrows():
  text = row['ReviewHeader']
  result = text_classifier(text)
  airline_reviews_df.loc[index, 'sentiment'] = result[0]['label']

In [42]:
airline_reviews_df.head(20)

,Unnamed: 0,OverallRating,ReviewHeader,Name,Datetime,VerifiedReview,ReviewBody,TypeOfTraveller,SeatType,Route,...,SeatComfort,CabinStaffService,GroundService,ValueForMoney,Recommended,Aircraft,Food&Beverages,InflightEntertainment,Wifi&Connectivity,sentiment
0,0,1.0,"""Service level far worse then Ryanair""",L Keele,19th November 2023,True,4 Hours before takeoff we received a Mail stat...,Couple Leisure,Economy Class,London to Stuttgart,...,1.0,1.0,1.0,1.0,no,NaN,NaN,NaN,NaN,NEGATIVE
1,1,3.0,"""do not upgrade members based on status""",Austin Jones,19th November 2023,True,I recently had a delay on British Airways from...,Business,Economy Class,Brussels to London,...,2.0,3.0,1.0,2.0,no,A320,1.0,2.0,2.0,NEGATIVE
2,2,8.0,"""Flight was smooth and quick""",M A Collie,16th November 2023,False,"Boarded on time, but it took ages to get to th...",Couple Leisure,Business Class,London Heathrow to Dublin,...,3.0,3.0,4.0,3.0,yes,A320,4.0,NaN,NaN,POSITIVE
3,3,1.0,"""Absolutely hopeless airline""",Nigel Dean,16th November 2023,True,"5 days before the flight, we were advised by B...",Couple Leisure,Economy Class,London to Dublin,...,3.0,3.0,1.0,1.0,no,NaN,NaN,NaN,NaN,NEGATIVE
4,4,1.0,"""Customer Service is non existent""",Gaylynne Simpson,14th November 2023,False,"We traveled to Lisbon for our dream vacation, ...",Couple Leisure,Economy Class,London to Lisbon,...,1.0,1.0,1.0,1.0,no,NaN,1.0,1.0,1.0,NEGATIVE
5,5,1.0,"""I can’t imagine a worst airline""",A Narden,12th November 2023,True,Booked a flight from Bucharest to Manchester w...,Solo Leisure,Economy Class,Bucharest to Manchester via London,...,1.0,1.0,1.0,1.0,no,A320,1.0,1.0,NaN,NEGATIVE
6,6,8.0,"""sufficient leg and arm room""",Graeme Boothman,8th November 2023,True,Booked online months ago and the only hitch wa...,Couple Leisure,Premium Economy,Manchester to Cape Town via London,...,5.0,5.0,4.0,4.0,yes,Boeing 777-300,4.0,4.0,NaN,POSITIVE
7,7,7.0,“crew were polite”,R Vines,7th November 2023,True,The flight was on time. The crew were polite. ...,Solo Leisure,Economy Class,Seville to London Gatwick,...,3.0,3.0,3.0,3.0,yes,A320,3.0,NaN,NaN,POSITIVE
8,8,2.0,"""Angry, disappointed, and unsatisfied""",Massimo Tricca,5th November 2023,False,"Angry, disappointed, and unsatisfied. My route...",Family Leisure,Economy Class,London Heatrow to Atlanta,...,4.0,5.0,3.0,5.0,yes,Boeing 777,4.0,4.0,3.0,NEGATIVE
9,9,3.0,"""BA now stands for Basic Airways""",J Kaye,5th November 2023,True,"As an infrequent flyer, British Airways was al...",Couple Leisure,Economy Class,Gatwick to Antalya,...,3.0,3.0,3.0,1.0,no,NaN,1.0,1.0,1.0,NEGATIVE
10,10,8.0,"""A totally unremarkable flight""",M Collie,4th November 2023,False,"A totally unremarkable flight, on time, as com...",Couple Leisure,Business Class,Dublin to London Heathrow,...,3.0,3.0,4.0,3.0,yes,A320,NaN,NaN,NaN,NEGATIVE
11,11,1.0,“BA clearly does not care”,J Furlong,31st October 2023,True,1. Ground crew in Heathrow left 60 passengers ...,Couple Leisure,Economy Class,Anchorage to Heathrow via Barcelona,...,3.0,3.0,1.0,1.0,no,NaN,3.0,3.0,3.0,NEGATIVE
12,12,6.0,"""reflect a downward trend of the airline""",C Barton,28th October 2023,True,London Heathrow to Gibraltar on 24th October 2...,Solo Leisure,Economy Class,London Heathrow to Gibraltar,...,3.0,1.0,3.0,2.0,no,A320,1.0,NaN,1.0,NEGATIVE
13,13,8.0,"""One of my better flights""",M Davidson,24th October 2023,True,First time flying British Airways and I would ...,Couple Leisure,Economy Class,London to Philadelphia,...,4.0,5.0,5.0,5.0,yes,NaN,4.0,3.0,NaN,POSITIVE
14,14,7.0,"""I would still recommend BA""",Michael Gardiner,23rd October 2023,False,I flew London to Cairo and return in October 2...,Business,Economy Class,London Heathrow to Cairo,...,3.0,5.0,5.0,2.0,yes,A321 neo,3.0,NaN,NaN,POSITIVE
15,15,1.0,"""the worst experience ever""",Terry Anderson,22nd October 2023,False,Absolutely the worst experience ever. Flew in...,Couple Leisure,Economy Class,Seattle to Porto via Heathrow,...,2.0,3.0,1.0,1.0,no,NaN,3.0,3.0,3.0,NEGATIVE
16,16,8.0,"""an exceptional crew member""",Philip Thompson,22nd October 2023,False,Flew back from Malta after scattering our son'...,Couple Leisure,Economy Class,Malta to London Gatwick,...,4.0,5.0,4.0,4.0,yes,A320,3.0,NaN,NaN,POSITIVE
17,17,3.0,"""even Ryanair have more space""",M Meijs,21st October 2023,False,"Cabin luggage had to go to cargo, even when I ...",Solo Leisure,Economy Class,London to Amsterdam,...,1.0,3.0,2.0,1.0,no,NaN,NaN,NaN,NaN,NEGATIVE
18,18,4.0,"""in-flight service is usually weak""",Mehmet Sahiner,21st October 2023,True,I have been using BA for a while now and on av...,Solo Leisure,Economy Class,San Francisco to London,...,3.0,2.0,2.0,3.0,no,A380-800,2.0,3.0,NaN,NEGATIVE
19,19,1.0,"""BA customer service is a disgrace""",T Meares,19th October 2023,True,I flew from Istanbul to London in Business cla...,Solo Leisure,Business Class,İstanbul to London,...,2.0,1.0,2.0,1.0,no,NaN,1.0,1.0,1.0,NEGATIVE

In [43]:
airline_reviews_df.value_counts('sentiment')

sentiment
NEGATIVE    40
POSITIVE    10
Name: count, dtype: int64